<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Broken_link</name>
   <tag></tag>
   <elementGuidId>1bf8af80-56fb-4d22-82e8-14cdf2dd6006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='http://the-internet.herokuapp.com/status_codes/500']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
