<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Valid_link</name>
   <tag></tag>
   <elementGuidId>db27314d-5cd6-4654-914a-cf741657e32f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='http://demoqa.com']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
